// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mlwqzkcwnmjeyobixwap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1sd3F6a2N3bm1qZXlvYml4d2FwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MTY4ODUsImV4cCI6MjA2OTI5Mjg4NX0.Kqzu2NYTj1HEx8CJPXji7F5Qtorab58_rklAolsgyrY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});